# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170315_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
