# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='mrp',
            field=models.CharField(default=100, max_length=30),
            preserve_default=False,
        ),
    ]
