# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
            ],
        ),
    ]
